# Generated by Django 4.1.3 on 2023-02-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='Info', max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
